#!/bin/bash

set -euo pipefail

# Reconfigure pre-commit hooks
if test -e .pre-commit-config.yaml
then
  pre-commit autoupdate
fi

# Install dependencies if lockfile changed
if test -e poetry.lock
then
  CHECKSUM_FILE=".poetry.lock.sha512sum"
  touch "$CHECKSUM_FILE"
  if [ "$(cat "$CHECKSUM_FILE")" != "$(sha512sum poetry.lock)" ]
  then
    poetry install --no-root
    sha512sum poetry.lock > "$CHECKSUM_FILE"
  fi
fi

# Apply migrations
if test -e manage.py
then
  MIGRATIONS_FILE=".migrations.local"
  touch "$MIGRATIONS_FILE"
  MIGRATIONS="$(git ls-files '**/migrations/*.py' | sort)"
  if [ "$(cat "$MIGRATIONS_FILE")" != "$MIGRATIONS" ]
  then
    ./manage.py migrate
    echo "$MIGRATIONS" > "$MIGRATIONS_FILE"
  fi
fi
