#!/bin/sh -eux

(dpkg -s gh > /dev/null) \
  || (
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
    sudo apt-add-repository -y https://cli.github.com/packages
    sudo apt update -qq
    sudo apt-get install -y gh
  )
