#!/bin/sh -eux

export CHSH=yes
export RUNZSH=no
export KEEP_ZSHRC=yes

# Install oh my zsh
[ -e ~/.oh-my-zsh ] \
  || sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
