#!/bin/sh -eux

TERRAFORM_VERSION="$(curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | jq -er ".tag_name[1:]")"
mkdir -p ~/.local/bin
curl -s "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" \
  | zcat > ~/.local/bin/terraform
chmod +x ~/.local/bin/terraform
